#!/usr/bin/env zsh

# Initial settings
source $HOME/.dotfiles/configs/.zshrc

# Install some dependencies
brew install gcc openssl readline xz zlib tcl-tk coreutils
brew install git wget curl tree jq yq tldr ipcalc redis sqlite3 awscli



# @see https://github.com/ggreer/the_silver_searcher ag
brew install the_silver_searcher

brew install ffmpeg

brew install --cask 1password
brew install --cask adguard
brew install --cask appcleaner
brew install --cask arc
brew install --cask aws-vpn-client
brew install --cask discord
brew install --cask orbstack
brew install --cask raycast
brew install --cask postman
brew install --cask slack
brew install --cask shottr
brew install --cask tableplus
brew install --cask telegram
brew install --cask visual-studio-code
brew install --cask warp

# install fonts
brew tap homebrew/cask-fonts
# terminal fonts
brew install --cask font-cascadia-code
brew install --cask font-cascadia-code-pl
brew install --cask font-cascadia-mono
brew install --cask font-cascadia-mono-pl
# IDE fonts
brew install --cask font-fira-code

success "Install homebrew packages successful."
exit 0
