#!/usr/bin/env zsh

# Initial settings
source $HOME/.dotfiles/configs/.zshrc

# Install some dependencies
brew install gcc openssl readline xz zlib tcl-tk coreutils
brew install git wget curl tree jq yq tldr ipcalc redis sqlite3 awscli



# @see https://github.com/ggreer/the_silver_searcher ag
brew install the_silver_searcher

brew install ffmpeg

brew install --cask slack
brew install --cask wrap
brew install --cask orbstack
brew install --cask visual-studio-code
brew install --cask postman
brew install --cask alfred
brew install --cask shottr
brew install --cask maccy
brew install --cask 1password
brew install --cask arc
brew install --cask tableplus

brew install --cask aws-vpn-client
brew install --cask 1password-cli


success "Install homebrew packages successful."
exit 0
